Update main_tech0-gen8-step4-pos-app-36.yml

diff --git a/.github/workflows/main_tech0-gen8-step4-pos-app-36.yml b/.github/workflows/main_tech0-gen8-step4-pos-app-36.yml
--- a/.github/workflows/main_tech0-gen8-step4-pos-app-36.yml
+++ b/.github/workflows/main_tech0-gen8-step4-pos-app-36.yml
@@ -1,6 +1,3 @@
-# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
-# More GitHub Actions for Azure: https://github.com/Azure/actions
-
 name: Build and deploy Node.js app to Azure Web App - tech0-gen8-step4-pos-app-36
 
 on:
@@ -23,7 +20,11 @@ jobs:
         run: ls -R
 
       - name: Check if package.json exists
-        run: test -f package.json || { echo "Error: package.json not found"; exit 1; }
+        run: |
+          if [ ! -f package.json ]; then
+            echo "Error: package.json not found"
+            exit 1
+          fi
 
       - name: Set up Node.js version
         uses: actions/setup-node@v3
@@ -35,7 +36,7 @@ jobs:
           npm install
           npm run build --if-present
           npm run test --if-present
-        working-directory: . # 必要に応じて `./your-app-directory` に変更
+        working-directory: .
 
       - name: Remove node_modules to reduce artifact size
         run: rm -rf node_modules
